In [121]:
import numpy as np

In [1114]:
A = np.random.rand(3,3)

In [1115]:
A

array([[0.06134647, 0.68662998, 0.87567362],
       [0.54215172, 0.16341624, 0.69483624],
       [0.6254462 , 0.67629913, 0.51864024]])

In [1134]:
def lu_factor(A):
    n = A.shape[0]
    P = np.identity(n)
    L = np.identity(n)
    U = A.copy()
    for k in range(n-1): # Loop over columns
        # Pivoting
        i = np.argmax(np.abs(U[k:,k]))+k # Maximum arg of current column
        if i != k:
            U[[i, k]] = U[[k,i]]   # Swap Rows
            P[[i, k]] = P[[k,i]]   # Save in pivot matrix
        
        # Updating L and U
        L[k+1:,k] = U[k+1:, k] / U[k,k]
        U[k+1:,k:] -= np.outer(L[k+1:,k], U[k:,k])
        print(U)
    return P, L, U

In [1135]:
P = np.identity(3)

P[[1, 2]] = P[[2,1]]   # Save in pivot matrix

In [1136]:
P, L, U = lu_factor(A)

[[ 0.6254462   0.67629913  0.51864024]
 [ 0.         -0.30653383  0.64165965]
 [ 0.          0.63345339  0.8696565 ]]
[[0.6254462  0.67629913 0.51864024]
 [0.         0.63345339 0.8696565 ]
 [0.         0.         0.49332515]]


In [1137]:
P

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [1138]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.8668239 ,  1.        ,  0.        ],
       [ 0.09808434, -0.48390906,  1.        ]])

In [1139]:
U

array([[0.6254462 , 0.67629913, 0.51864024],
       [0.        , 0.63345339, 0.8696565 ],
       [0.        , 0.        , 0.49332515]])

In [1140]:
P

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [1141]:
L @ U

array([[ 0.6254462 ,  0.67629913,  0.51864024],
       [ 0.54215172,  1.21968565,  1.31922626],
       [ 0.06134647, -0.24019948,  0.12336098]])

In [1142]:
P @ A

array([[0.6254462 , 0.67629913, 0.51864024],
       [0.06134647, 0.68662998, 0.87567362],
       [0.54215172, 0.16341624, 0.69483624]])

In [1063]:
np.isclose(P @ A,  L@U) # Is this sufficiently close

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [1064]:
 np.max(P @ A -  L @ U)

1.2837724406517077

In [951]:
np.linalg.cond(A)

12.52219116575754

In [952]:
U

array([[  1.10898424,  -0.57192932,  -0.48849079,  -2.26618113,
         -0.24847424],
       [  0.        ,   0.        ,   2.96125756,  -5.50372719,
          1.16097897],
       [  0.        ,  -0.49280015,   0.57869482,  -0.58353313,
         -1.28196671],
       [  0.        ,   0.        ,   0.        , -96.06100305,
         34.42585818],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         -0.8999888 ]])